### ISSUE TITLE
Could not find com.github.jonz94:TedImagePicker:1.5.0.3

### ISSUE THREAD

**Issue by ajayvermapsit** [jonz94/capacitor-image-picker#16]
Hi,
I have ionic-react app where using this plugin , but when creating android build getting these errors, although done all the changes mentioned in the documentation:
execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.jonz94:TedImagePicker:1.5.0.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/jonz94/TedImagePicker/1.5.0.3/TedImagePicker-1.5.0.3.pom
       - https://repo.maven.apache.org/maven2/com/github/jonz94/TedImagePicker/1.5.0.3/TedImagePicker-1.5.0.3.pom
       - file:/Users/unthinkable-mac/Desktop/ionic8-app/android/capacitor-cordova-android-plugins/src/main/libs/TedImagePicker-1.5.0.3.jar
       - file:/Users/unthinkable-mac/Desktop/ionic8-app/android/capacitor-cordova-android-plugins/src/main/libs/TedImagePicker.jar
       - file:/Users/unthinkable-mac/Desktop/ionic8-app/android/app/libs/TedImagePicker-1.5.0.3.jar
       - file:/Users/unthinkable-mac/Desktop/ionic8-app/android/app/libs/TedImagePicker.jar
     Required by:
         project :app > project :jonz94-capacitor-image-picker

seems like these libraries has been removed, as when opening these links:
https://dl.google.com/dl/android/maven2/com/github/jonz94/TedImagePicker/1.5.0.3/TedImagePicker-1.5.0.3.pom,
https://repo.maven.apache.org/maven2/com/github/jonz94/TedImagePicker/1.5.0.3/TedImagePicker-1.5.0.3.pom

getting error that file is not found, can anyone help,

additional information:
   Ionic Framework : @ionic/react 8.3.0
     @capacitor/android : 6.1.2
   @capacitor/core    : 6.1.2
   @capacitor/ios     : 6.1.2

   NodeJS : v18.19.1
   npm    : 10.2.4

**Comment by jonz94** [comment]
Hi, this plugin for Android is published on JitPack (https://jitpack.io/#jonz94/TedImagePicker)

Therefore, you will need to setup JitPack repository for your android project.

See: https://github.com/jonz94/capacitor-image-picker#android

![image](https://github.com/user-attachments/assets/cd07f02c-2b33-424b-8792-79ceba8fa040)

After that, the issue should be resolved.

**Comment by ajayvermapsit** [comment]
@jonz94 Yes, issue has been resolve , I had added this:  maven { url "https://jitpack.io" } , under  buildscript { repositories { }} , but in allprojects {  repositories { }}

But I thing we also need to do is that compileSdkVersion and targetSdkVersion should be 34
